### ISSUE TITLE
No longer reads .jxl files

### ISSUE THREAD

**Issue by alastortenebris** [flathub/com.yacreader.YACReader#10]
The latest update seems to have broken YACReader's ability to read .jxl files.

**Comment by selmf** [comment]
.jxl is not (and never was) part of YACReader's supported file formats

**Comment by alastortenebris** [comment]
Oh, I think I see what happened. YACReader was able to read jxl files through KImageFormats, which is a QT5 plugin. Since YACReader now uses QT6, it no longer works.

**Comment by selmf** [comment]
Yes, that probably is the case. You can wait for the Kde Flatpak runtime team to add it once a Qt6 version is production ready or maybe request them to add it earlier.

I'd also be willing to review a PR that adds it or an alternative plugin to the YACReader Flatpak build.
